name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bash-version: ['4.4', '5.0', '5.1']

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bash ${{ matrix.bash-version }}
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y bash=${{ matrix.bash-version }}*
    
    - name: Make scripts executable
      run: chmod +x godspeed.sh scripts/*.sh test/*.sh
    
    - name: Lint with shellcheck
      run: |
        sudo apt-get install -y shellcheck || brew install shellcheck
        make lint
    
    - name: Run tests
      run: make test
    
    - name: Test installation
      run: ./test/test-installation.sh

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security scan
      run: |
        echo "Running security checks..."
